# Generated by Django 5.1 on 2024-08-12 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheatsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to='cheatsheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, null=True)),
                ('progress', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('text', models.CharField(max_length=2000, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('production_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
                ('grade', models.CharField(max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cheatsheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.cheatsheet')),
            ],
        ),
    ]
