# Generated by Django 5.1 on 2024-08-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='download_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
