# Generated by Django 5.1 on 2024-08-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_post_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='download_count',
        ),
    ]
