# Generated by Django 5.1 on 2024-08-20 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='old',
            name='header',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Mov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('text', models.CharField(max_length=2000, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('production_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
                ('grade', models.CharField(max_length=200, null=True)),
                ('cheatsheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.cheatsheet')),
            ],
        ),
        migrations.CreateModel(
            name='Tato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('text', models.CharField(max_length=2000, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('production_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
                ('grade', models.CharField(max_length=200, null=True)),
                ('cheatsheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.cheatsheet')),
            ],
        ),
    ]
