# Generated by Django 5.1 on 2024-08-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_old_header_mov_tato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tato',
            name='header',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
